export type Country = {
    flag: string;
    name: string;
    nameFr: string;
    nameAr: string;
    code: string;
    dialCode: string;
   };
   
   export const getAllCountries = (): Country[] => {
    return [
    {
    flag: "🇲🇷",
    name: "Mauritania",
    nameFr: "Mauritanie",
    nameAr: "موريتانيا",
    code: "MR",
    dialCode: "+222",
    },
    {
    flag: "🇦🇫",
    name: "Afghanistan",
    nameFr: "Afghanistan",
    nameAr: "أفغانستان",
    code: "AF",
    dialCode: "+93",
    },
    {
    flag: "🇦🇽",
    name: "Åland Islands",
    nameFr: "Åland Islands",
    nameAr: "جزر أولاند",
    code: "AX",
    dialCode: "+358",
    },
    {
    flag: "🇦🇱",
    name: "Albania",
    nameFr: "Albania",
    nameAr: "ألبانيا",
    code: "AL",
    dialCode: "+355",
    },
    {
    flag: "🇩🇿",
    name: "Algeria",
    nameFr: "Algeria",
    nameAr: "الجزائر",
    code: "DZ",
    dialCode: "+213",
    },
    {
    flag: "🇦🇸",
    name: "American Samoa",
    nameFr: "American Samoa",
    nameAr: "ساموا الأمريكية",
    code: "AS",
    dialCode: "+1684",
    },
    {
    flag: "🇦🇩",
    name: "Andorra",
    nameFr: "Andorra",
    nameAr: "أندورا",
    code: "AD",
    dialCode: "+376",
    },
    {
    flag: "🇦🇴",
    name: "Angola",
    nameFr: "Angola",
    nameAr: "أنغولا",
    code: "AO",
    dialCode: "+244",
    },
    {
    flag: "🇦🇮",
    name: "Anguilla",
    nameFr: "Anguilla",
    nameAr: "أنغويلا",
    code: "AI",
    dialCode: "+1264",
    },
    {
    flag: "🇦🇶",
    name: "Antarctica",
    nameFr: "Antarctica",
    nameAr: "أنتاركتيكا",
    code: "AQ",
    dialCode: "+672",
    },
    {
    flag: "🇦🇷",
    name: "Argentina",
    nameFr: "Argentine",
    nameAr: "الأرجنتين",
    code: "AR",
    dialCode: "+54",
    },
    {
    flag: "🇦🇲",
    name: "Armenia",
    nameFr: "Arménie",
    nameAr: "أرمينيا",
    code: "AM",
    dialCode: "+374",
    },
    {
    flag: "🇦🇼",
    name: "Aruba",
    nameFr: "Aruba",
    nameAr: "أروبا",
    code: "AW",
    dialCode: "+297",
    },
    {
    flag: "🇦🇺",
    name: "Australia",
    nameFr: "Australie",
    nameAr: "أستراليا",
    code: "AU",
    dialCode: "+61",
    },
    {
    flag: "🇦🇹",
    name: "Austria",
    nameFr: "Autriche",
    nameAr: "النمسا",
    code: "AT",
    dialCode: "+43",
    },
    {
    flag: "🇦🇿",
    name: "Azerbaijan",
    nameFr: "Azerbaïdjan",
    nameAr: "أذربيجان",
    code: "AZ",
    dialCode: "+994",
    },
    {
    flag: "🇧🇸",
    name: "Bahamas",
    nameFr: "Bahamas",
    nameAr: "الباهاما",
    code: "BS",
    dialCode: "+1242",
    },
    {
    flag: "🇧🇭",
    name: "Bahrain",
    nameFr: "Bahreïn",
    nameAr: "البحرين",
    code: "BH",
    dialCode: "+973",
    },
    {
    flag: "🇧🇩",
    name: "Bangladesh",
    nameFr: "Bangladesh",
    nameAr: "بنغلاديش",
    code: "BD",
    dialCode: "+880",
    },
    {
    flag: "🇧🇧",
    name: "Barbados",
    nameFr: "Barbade",
    nameAr: "بربادوس",
    code: "BB",
    dialCode: "+1246",
    },
    {
    flag: "🇧🇾",
    name: "Belarus",
    nameFr: "Biélorussie",
    nameAr: "بيلاروسيا",
    code: "BY",
    dialCode: "+375",
    },
    {
    flag: "🇧🇪",
    name: "Belgium",
    nameFr: "Belgique",
    nameAr: "بلجيكا",
    code: "BE",
    dialCode: "+32",
    },
    {
    flag: "🇧🇿",
    name: "Belize",
    nameFr: "Belize",
    nameAr: "بليز",
    code: "BZ",
    dialCode: "+501",
    },
    {
    flag: "🇧🇯",
    name: "Benin",
    nameFr: "Bénin",
    nameAr: "بنين",
    code: "BJ",
    dialCode: "+229",
    },
    {
    flag: "🇧🇲",
    name: "Bermuda",
    nameFr: "Bermudes",
    nameAr: "برمودا",
    code: "BM",
    dialCode: "+1441",
    },
    {
    flag: "🇧🇹",
    name: "Bhutan",
    nameFr: "Bhoutan",
    nameAr: "بوتان",
    code: "BT",
    dialCode: "+975",
    },
    {
    flag: "🇧🇴",
    name: "Bolivia",
    nameFr: "Bolivie",
    nameAr: "بوليفيا",
    code: "BO",
    dialCode: "+591",
    },
    {
    flag: "🇧🇶",
    name: "Bonaire, Sint Eustatius and Saba",
    nameFr: "Bonaire, Saint-Eustache et Saba",
    nameAr: "بونير، سينت يوستاتيوس، وصابا",
    code: "BQ",
    dialCode: "+5997",
    },
    {
    flag: "🇧🇦",
    name: "Bosnia and Herzegovina",
    nameFr: "Bosnie-Herzégovine",
    nameAr: "البوسنة والهرسك",
    code: "BA",
    dialCode: "+387",
    },
    {
    flag: "🇧🇼",
    name: "Botswana",
    nameFr: "Botswana",
    nameAr: "بوتسوانا",
    code: "BW",
    dialCode: "+267",
    },
    {
    flag: "🇧🇷",
    name: "Brazil",
    nameFr: "Brésil",
    nameAr: "البرازيل",
    code: "BR",
    dialCode: "+55",
    },
    {
    flag: "🇧🇳",
    name: "Brunei",
    nameFr: "Brunéi",
    nameAr: "بروناي",
    code: "BN",
    dialCode: "+673",
    },
    {
    flag: "🇧🇬",
    name: "Bulgaria",
    nameFr: "Bulgarie",
    nameAr: "بلغاريا",
    code: "BG",
    dialCode: "+359",
    },
    {
    flag: "🇧🇫",
    name: "Burkina Faso",
    nameFr: "Burkina Faso",
    nameAr: "بوركينا فاسو",
    code: "BF",
    dialCode: "+226",
    },
    {
    flag: "🇧🇮",
    name: "Burundi",
    nameFr: "Burundi",
    nameAr: "بوروندي",
    code: "BI",
    dialCode: "+257",
    },
    {
    flag: "🇨🇻",
    name: "Cabo Verde",
    nameFr: "Cap-Vert",
    nameAr: "الرأس الأخضر",
    code: "CV",
    dialCode: "+238",
    },
    {
    flag: "🇰🇭",
    name: "Cambodia",
    nameFr: "Cambodge",
    nameAr: "كمبوديا",
    code: "KH",
    dialCode: "+855",
    },
    {
    flag: "🇨🇲",
    name: "Cameroon",
    nameFr: "Cameroun",
    nameAr: "الكاميرون",
    code: "CM",
    dialCode: "+237",
    },
    {
    flag: "🇨🇦",
    name: "Canada",
    nameFr: "Canada",
    nameAr: "كندا",
    code: "CA",
    dialCode: "+1",
    },
    {
    flag: "🇰🇾",
    name: "Cayman Islands",
    nameFr: "Îles Caïmans",
    nameAr: "جزر كايمان",
    code: "KY",
    dialCode: "+1345",
    },
    {
    flag: "🇨🇫",
    name: "Central African Republic",
    nameFr: "République centrafricaine",
    nameAr: "جمهورية أفريقيا الوسطى",
    code: "CF",
    dialCode: "+236",
    },
    {
    flag: "🇹🇩",
    name: "Chad",
    nameFr: "Tchad",
    nameAr: "تشاد",
    code: "TD",
    dialCode: "+235",
    },
    {
    flag: "🇨🇱",
    name: "Chile",
    nameFr: "Chili",
    nameAr: "تشيلي",
    code: "CL",
    dialCode: "+56",
    },
    {
    flag: "🇨🇳",
    name: "China",
    nameFr: "Chine",
    nameAr: "الصين",
    code: "CN",
    dialCode: "+86",
    },
    {
    flag: "🇨🇽",
    name: "Christmas Island",
    nameFr: "Île de Noël",
    nameAr: "جزيرة الكريسماس",
    code: "CX",
    dialCode: "+61",
    },
    {
    flag: "🇨🇨",
    name: "Cocos (Keeling) Islands",
    nameFr: "Îles Cocos (Keeling)",
    nameAr: "جزر كوكوس (كيلينغ)",
    code: "CC",
    dialCode: "+61",
    },
    {
    flag: "🇨🇴",
    name: "Colombia",
    nameFr: "Colombie",
    nameAr: "كولومبيا",
    code: "CO",
    dialCode: "+57",
    },
    {
    flag: "🇰🇲",
    name: "Comoros",
    nameFr: "Comores",
    nameAr: "جزر القمر",
    code: "KM",
    dialCode: "+269",
    },
    {
    flag: "🇨🇬",
    name: "Congo",
    nameFr: "Congo",
    nameAr: "الكونغو",
    code: "CG",
    dialCode: "+242",
    },
    {
    flag: "🇨🇩",
    name: "Congo (Democratic Republic of the)",
    nameFr: "Congo (République démocratique du)",
    nameAr: "الكونغو (جمهورية الكونغو الديمقراطية)",
    code: "CD",
    dialCode: "+243",
    },
    {
    flag: "🇨🇰",
    name: "Cook Islands",
    nameFr: "Îles Cook",
    nameAr: "جزر كوك",
    code: "CK",
    dialCode: "+682",
    },
    {
    flag: "🇨🇷",
    name: "Costa Rica",
    nameFr: "Costa Rica",
    nameAr: "كوستاريكا",
    code: "CR",
    dialCode: "+506",
    },
    {
    flag: "🇨🇮",
    name: "Côte d'Ivoire",
    nameFr: "Côte d'Ivoire",
    nameAr: "ساحل العاج",
    code: "CI",
    dialCode: "+225",
    },
    {
    flag: "🇭🇷",
    name: "Croatia",
    nameFr: "Croatie",
    nameAr: "كرواتيا",
    code: "HR",
    dialCode: "+385",
    },
    {
    flag: "🇨🇺",
    name: "Cuba",
    nameFr: "Cuba",
    nameAr: "كوبا",
    code: "CU",
    dialCode: "+53",
    },
    {
    flag: "🇨🇾",
    name: "Cyprus",
    nameFr: "Chypre",
    nameAr: "قبرص",
    code: "CY",
    dialCode: "+357",
    },
    {
    flag: "🇨🇿",
    name: "Czech Republic",
    nameFr: "République tchèque",
    nameAr: "جمهورية التشيك",
    code: "CZ",
    dialCode: "+420",
    },
    {
    flag: "🇩🇰",
    name: "Denmark",
    nameFr: "Danemark",
    nameAr: "الدنمارك",
    code: "DK",
    dialCode: "+45",
    },
    {
    flag: "🇩🇯",
    name: "Djibouti",
    nameFr: "Djibouti",
    nameAr: "جيبوتي",
    code: "DJ",
    dialCode: "+253",
    },
    {
    flag: "🇩🇲",
    name: "Dominica",
    nameFr: "Dominique",
    nameAr: "دومينيكا",
    code: "DM",
    dialCode: "+1767",
    },
    {
    flag: "🇩🇴",
    name: "Dominican Republic",
    nameFr: "République dominicaine",
    nameAr: "جمهورية الدومينيكان",
    code: "DO",
    dialCode: "+1809",
    },
    {
    flag: "🇪🇨",
    name: "Ecuador",
    nameFr: "Équateur",
    nameAr: "الإكوادور",
    code: "EC",
    dialCode: "+593",
    },
    {
    flag: "🇪🇬",
    name: "Egypt",
    nameFr: "Égypte",
    nameAr: "مصر",
    code: "EG",
    dialCode: "+20",
    },
    {
    flag: "🇸🇻",
    name: "El Salvador",
    nameFr: "Salvador",
    nameAr: "السلفادور",
    code: "SV",
    dialCode: "+503",
    },
    {
    flag: "🇬🇶",
    name: "Equatorial Guinea",
    nameFr: "Guinée équatoriale",
    nameAr: "غينيا الاستوائية",
    code: "GQ",
    dialCode: "+240",
    },
    {
    flag: "🇪🇷",
    name: "Eritrea",
    nameFr: "Érythrée",
    nameAr: "إريتريا",
    code: "ER",
    dialCode: "+291",
    },
    {
    flag: "🇪🇪",
    name: "Estonia",
    nameFr: "Estonie",
    nameAr: "إستونيا",
    code: "EE",
    dialCode: "+372",
    },
    {
    flag: "🇪🇹",
    name: "Ethiopia",
    nameFr: "Éthiopie",
    nameAr: "إثيوبيا",
    code: "ET",
    dialCode: "+251",
    },
    {
    flag: "🇫🇰",
    name: "Falkland Islands (Malvinas)",
    nameFr: "Îles Falkland (Malvinas)",
    nameAr: "جزر فوكلاند (مالفيناس)",
    code: "FK",
    dialCode: "+500",
    },
    {
    flag: "🇫🇴",
    name: "Faroe Islands",
    nameFr: "Îles Féroé",
    nameAr: "جزر فارو",
    code: "FO",
    dialCode: "+298",
    },
    {
    flag: "🇫🇯",
    name: "Fiji",
    nameFr: "Fidji",
    nameAr: "فيجي",
    code: "FJ",
    dialCode: "+679",
    },
    {
    flag: "🇫🇮",
    name: "Finland",
    nameFr: "Finlande",
    nameAr: "فنلندا",
    code: "FI",
    dialCode: "+358",
    },
    {
    flag: "🇫🇷",
    name: "France",
    nameFr: "France",
    nameAr: "فرنسا",
    code: "FR",
    dialCode: "+33",
    },
    {
    flag: "🇬🇫",
    name: "French Guiana",
    nameFr: "Guyane française",
    nameAr: "غويانا الفرنسية",
    code: "GF",
    dialCode: "+594",
    },
    {
    flag: "🇵🇫",
    name: "French Polynesia",
    nameFr: "Polynésie française",
    nameAr: "بولينيزيا الفرنسية",
    code: "PF",
    dialCode: "+689",
    },
    {
    flag: "🇬🇦",
    name: "Gabon",
    nameFr: "Gabon",
    nameAr: "الغابون",
    code: "GA",
    dialCode: "+241",
    },
    {
    flag: "🇬🇲",
    name: "Gambia",
    nameFr: "Gambie",
    nameAr: "غامبيا",
    code: "GM",
    dialCode: "+220",
    },
    {
    flag: "🇬🇪",
    name: "Georgia",
    nameFr: "Géorgie",
    nameAr: "جورجيا",
    code: "GE",
    dialCode: "+995",
    },
    {
    flag: "🇩🇪",
    name: "Germany",
    nameFr: "Allemagne",
    nameAr: "ألمانيا",
    code: "DE",
    dialCode: "+49",
    },
    {
    flag: "🇬🇭",
    name: "Ghana",
    nameFr: "Ghana",
    nameAr: "غانا",
    code: "GH",
    dialCode: "+233",
    },
    {
    flag: "🇬🇮",
    name: "Gibraltar",
    nameFr: "Gibraltar",
    nameAr: "جبل طارق",
    code: "GI",
    dialCode: "+350",
    },
    {
    flag: "🇬🇷",
    name: "Greece",
    nameFr: "Grèce",
    nameAr: "اليونان",
    code: "GR",
    dialCode: "+30",
    },
    {
    flag: "🇬🇱",
    name: "Greenland",
    nameFr: "Groenland",
    nameAr: "جرينلاند",
    code: "GL",
    dialCode: "+299",
    },
    {
    flag: "🇬🇩",
    name: "Grenada",
    nameFr: "Grenade",
    nameAr: "غرينادا",
    code: "GD",
    dialCode: "+1473",
    },
    {
    flag: "🇬🇵",
    name: "Guadeloupe",
    nameFr: "Guadeloupe",
    nameAr: "غوادلوب",
    code: "GP",
    dialCode: "+590",
    },
    {
    flag: "🇬🇺",
    name: "Guam",
    nameFr: "Guam",
    nameAr: "غوام",
    code: "GU",
    dialCode: "+1671",
    },
    {
    flag: "🇬🇹",
    name: "Guatemala",
    nameFr: "Guatemala",
    nameAr: "غواتيمالا",
    code: "GT",
    dialCode: "+502",
    },
    {
    flag: "🇬🇬",
    name: "Guernsey",
    nameFr: "Guernesey",
    nameAr: "غيرنزي",
    code: "GG",
    dialCode: "+44",
    },
    {
    flag: "🇬🇳",
    name: "Guinea",
    nameFr: "Guinée",
    nameAr: "غينيا",
    code: "GN",
    dialCode: "+224",
    },
    {
    flag: "🇬🇼",
    name: "Guinea-Bissau",
    nameFr: "Guinée-Bissau",
    nameAr: "غينيا بيساو",
    code: "GW",
    dialCode: "+245",
    },
    {
    flag: "🇬🇾",
    name: "Guyana",
    nameFr: "Guyane",
    nameAr: "غيانا",
    code: "GY",
    dialCode: "+592",
    },
    {
    flag: "🇭🇹",
    name: "Haiti",
    nameFr: "Haïti",
    nameAr: "هايتي",
    code: "HT",
    dialCode: "+509",
    },
    {
    flag: "🇭🇳",
    name: "Honduras",
    nameFr: "Honduras",
    nameAr: "هندوراس",
    code: "HN",
    dialCode: "+504",
    },
    {
    flag: "🇭🇰",
    name: "Hong Kong",
    nameFr: "Hong Kong",
    nameAr: "هونغ كونغ",
    code: "HK",
    dialCode: "+852",
    },
    {
    flag: "🇭🇺",
    name: "Hungary",
    nameFr: "Hongrie",
    nameAr: "هنغاريا",
    code: "HU",
    dialCode: "+36",
    },
    {
    flag: "🇮🇸",
    name: "Iceland",
    nameFr: "Islande",
    nameAr: "آيسلندا",
    code: "IS",
    dialCode: "+354",
    },
    {
    flag: "🇮🇳",
    name: "India",
    nameFr: "Inde",
    nameAr: "الهند",
    code: "IN",
    dialCode: "+91",
    },
    {
    flag: "🇮🇩",
    name: "Indonesia",
    nameFr: "Indonésie",
    nameAr: "إندونيسيا",
    code: "ID",
    dialCode: "+62",
    },
    {
    flag: "🇮🇷",
    name: "Iran",
    nameFr: "Iran",
    nameAr: "إيران",
    code: "IR",
    dialCode: "+98",
    },
    {
    flag: "🇮🇶",
    name: "Iraq",
    nameFr: "Irak",
    nameAr: "العراق",
    code: "IQ",
    dialCode: "+964",
    },
    {
    flag: "🇮🇪",
    name: "Ireland",
    nameFr: "Irlande",
    nameAr: "أيرلندا",
    code: "IE",
    dialCode: "+353",
    },
    {
    flag: "🇮🇲",
    name: "Isle of Man",
    nameFr: "Île de Man",
    nameAr: "جزيرة مان",
    code: "IM",
    dialCode: "+44",
    },
    {
    flag: "🇮🇹",
    name: "Italy",
    nameFr: "Italie",
    nameAr: "إيطاليا",
    code: "IT",
    dialCode: "+39",
    },
    {
    flag: "🇯🇲",
    name: "Jamaica",
    nameFr: "Jamaïque",
    nameAr: "جامايكا",
    code: "JM",
    dialCode: "+1876",
    },
    {
    flag: "🇯🇵",
    name: "Japan",
    nameFr: "Japon",
    nameAr: "اليابان",
    code: "JP",
    dialCode: "+81",
    },
    {
    flag: "🇯🇪",
    name: "Jersey",
    nameFr: "Jersey",
    nameAr: "جيرسي",
    code: "JE",
    dialCode: "+44",
    },
    {
    flag: "🇯🇴",
    name: "Jordan",
    nameFr: "Jordanie",
    nameAr: "الأردن",
    code: "JO",
    dialCode: "+962",
    },
    {
    flag: "🇰🇿",
    name: "Kazakhstan",
    nameFr: "Kazakhstan",
    nameAr: "كازاخستان",
    code: "KZ",
    dialCode: "+7",
    },
    {
    flag: "🇰🇪",
    name: "Kenya",
    nameFr: "Kenya",
    nameAr: "كينيا",
    code: "KE",
    dialCode: "+254",
    },
    {
    flag: "🇰🇮",
    name: "Kiribati",
    nameFr: "Kiribati",
    nameAr: "كيريباتي",
    code: "KI",
    dialCode: "+686",
    },
    {
    flag: "🇽🇰",
    name: "Kosovo",
    nameFr: "Kosovo",
    nameAr: "كوسوفو",
    code: "XK",
    dialCode: "+383",
    },
    {
    flag: "🇰🇼",
    name: "Kuwait",
    nameFr: "Koweït",
    nameAr: "الكويت",
    code: "KW",
    dialCode: "+965",
    },
    {
    flag: "🇰🇬",
    name: "Kyrgyzstan",
    nameFr: "Kirghizistan",
    nameAr: "قرغيزستان",
    code: "KG",
    dialCode: "+996",
    },
    {
    flag: "🇱🇦",
    name: "Laos",
    nameFr: "Laos",
    nameAr: "لاوس",
    code: "LA",
    dialCode: "+856",
    },
    {
    flag: "🇱🇻",
    name: "Latvia",
    nameFr: "Lettonie",
    nameAr: "لاتفيا",
    code: "LV",
    dialCode: "+371",
    },
    {
    flag: "🇱🇧",
    name: "Lebanon",
    nameFr: "Liban",
    nameAr: "لبنان",
    code: "LB",
    dialCode: "+961",
    },
    {
    flag: "🇱🇸",
    name: "Lesotho",
    nameFr: "Lesotho",
    nameAr: "ليسوتو",
    code: "LS",
    dialCode: "+266",
    },
    {
    flag: "🇱🇷",
    name: "Liberia",
    nameFr: "Libéria",
    nameAr: "ليبيريا",
    code: "LR",
    dialCode: "+231",
    },
    {
    flag: "🇱🇾",
    name: "Libya",
    nameFr: "Libye",
    nameAr: "ليبيا",
    code: "LY",
    dialCode: "+218",
    },
    {
    flag: "🇱🇮",
    name: "Liechtenstein",
    nameFr: "Liechtenstein",
    nameAr: "ليختنشتاين",
    code: "LI",
    dialCode: "+423",
    },
    {
    flag: "🇱🇹",
    name: "Lithuania",
    nameFr: "Lituanie",
    nameAr: "ليتوانيا",
    code: "LT",
    dialCode: "+370",
    },
    {
    flag: "🇱🇺",
    name: "Luxembourg",
    nameFr: "Luxembourg",
    nameAr: "لوكسمبورغ",
    code: "LU",
    dialCode: "+352",
    },
    {
    flag: "🇲🇴",
    name: "Macao",
    nameFr: "Macao",
    nameAr: "ماكاو",
    code: "MO",
    dialCode: "+853",
    },
    {
    flag: "🇲🇰",
    name: "North Macedonia",
    nameFr: "Macédoine du Nord",
    nameAr: "مقدونيا الشمالية",
    code: "MK",
    dialCode: "+389",
    },
    {
    flag: "🇲🇬",
    name: "Madagascar",
    nameFr: "Madagascar",
    nameAr: "مدغشقر",
    code: "MG",
    dialCode: "+261",
    },
    {
    flag: "🇲🇼",
    name: "Malawi",
    nameFr: "Malawi",
    nameAr: "مالاوي",
    code: "MW",
    dialCode: "+265",
    },
    {
    flag: "🇲🇾",
    name: "Malaysia",
    nameFr: "Malaisie",
    nameAr: "ماليزيا",
    code: "MY",
    dialCode: "+60",
    },
    {
    flag: "🇲🇻",
    name: "Maldives",
    nameFr: "Maldives",
    nameAr: "جزر المالديف",
    code: "MV",
    dialCode: "+960",
    },
    {
    flag: "🇲🇱",
    name: "Mali",
    nameFr: "Mali",
    nameAr: "مالي",
    code: "ML",
    dialCode: "+223",
    },
    {
    flag: "🇲🇹",
    name: "Malta",
    nameFr: "Malte",
    nameAr: "مالطا",
    code: "MT",
    dialCode: "+356",
    },
    {
    flag: "🇲🇭",
    name: "Marshall Islands",
    nameFr: "Îles Marshall",
    nameAr: "جزر مارشال",
    code: "MH",
    dialCode: "+692",
    },
    {
    flag: "🇲🇶",
    name: "Martinique",
    nameFr: "Martinique",
    nameAr: "مارتينيك",
    code: "MQ",
    dialCode: "+596",
    },
    {
    flag: "🇲🇺",
    name: "Mauritius",
    nameFr: "Maurice",
    nameAr: "موريشيوس",
    code: "MU",
    dialCode: "+230",
    },
    {
    flag: "🇾🇹",
    name: "Mayotte",
    nameFr: "Mayotte",
    nameAr: "مايوت",
    code: "YT",
    dialCode: "+262",
    },
    {
    flag: "🇲🇽",
    name: "Mexico",
    nameFr: "Mexique",
    nameAr: "المكسيك",
    code: "MX",
    dialCode: "+52",
    },
    {
    flag: "🇫🇲",
    name: "Micronesia",
    nameFr: "Micronésie",
    nameAr: "ميكرونيزيا",
    code: "FM",
    dialCode: "+691",
    },
    {
    flag: "🇲🇩",
    name: "Moldova",
    nameFr: "Moldavie",
    nameAr: "مولدوفا",
    code: "MD",
    dialCode: "+373",
    },
    {
    flag: "🇲🇨",
    name: "Monaco",
    nameFr: "Monaco",
    nameAr: "موناكو",
    code: "MC",
    dialCode: "+377",
    },
    {
    flag: "🇲🇳",
    name: "Mongolia",
    nameFr: "Mongolie",
    nameAr: "منغوليا",
    code: "MN",
    dialCode: "+976",
    },
    {
    flag: "🇲🇪",
    name: "Montenegro",
    nameFr: "Monténégro",
    nameAr: "الجبل الأسود",
    code: "ME",
    dialCode: "+382",
    },
    {
    flag: "🇲🇸",
    name: "Montserrat",
    nameFr: "Montserrat",
    nameAr: "مونتسيرات",
    code: "MS",
    dialCode: "+1664",
    },
    {
    flag: "🇲🇦",
    name: "Morocco",
    nameFr: "Maroc",
    nameAr: "المغرب",
    code: "MA",
    dialCode: "+212",
    },
    {
    flag: "🇲🇿",
    name: "Mozambique",
    nameFr: "Mozambique",
    nameAr: "موزمبيق",
    code: "MZ",
    dialCode: "+258",
    },
    {
    flag: "🇲🇲",
    name: "Myanmar",
    nameFr: "Myanmar",
    nameAr: "ميانمار",
    code: "MM",
    dialCode: "+95",
    },
    {
    flag: "🇳🇦",
    name: "Namibia",
    nameFr: "Namibie",
    nameAr: "ناميبيا",
    code: "NA",
    dialCode: "+264",
    },
    {
    flag: "🇳🇷",
    name: "Nauru",
    nameFr: "Nauru",
    nameAr: "ناورو",
    code: "NR",
    dialCode: "+674",
    },
    {
    flag: "🇳🇵",
    name: "Nepal",
    nameFr: "Népal",
    nameAr: "نيبال",
    code: "NP",
    dialCode: "+977",
    },
    {
    flag: "🇳🇱",
    name: "Netherlands",
    nameFr: "Pays-Bas",
    nameAr: "هولندا",
    code: "NL",
    dialCode: "+31",
    },
    {
    flag: "🇳🇨",
    name: "New Caledonia",
    nameFr: "Nouvelle-Calédonie",
    nameAr: "كاليدونيا الجديدة",
    code: "NC",
    dialCode: "+687",
    },
    {
    flag: "🇳🇿",
    name: "New Zealand",
    nameFr: "Nouvelle-Zélande",
    nameAr: "نيوزيلندا",
    code: "NZ",
    dialCode: "+64",
    },
    {
    flag: "🇳🇮",
    name: "Nicaragua",
    nameFr: "Nicaragua",
    nameAr: "نيكاراغوا",
    code: "NI",
    dialCode: "+505",
    },
    {
    flag: "🇳🇪",
    name: "Niger",
    nameFr: "Niger",
    nameAr: "النيجر",
    code: "NE",
    dialCode: "+227",
    },
    {
    flag: "🇳🇬",
    name: "Nigeria",
    nameFr: "Nigéria",
    nameAr: "نيجيريا",
    code: "NG",
    dialCode: "+234",
    },
    {
    flag: "🇳🇺",
    name: "Niue",
    nameFr: "Niue",
    nameAr: "نيوي",
    code: "NU",
    dialCode: "+683",
    },
    {
    flag: "🇳🇫",
    name: "Norfolk Island",
    nameFr: "Île Norfolk",
    nameAr: "جزيرة نورفولك",
    code: "NF",
    dialCode: "+672",
    },
    {
    flag: "🇲🇵",
    name: "Northern Mariana Islands",
    nameFr: "Îles Mariannes du Nord",
    nameAr: "جزر ماريانا الشمالية",
    code: "MP",
    dialCode: "+1670",
    },
    {
    flag: "🇳🇴",
    name: "Norway",
    nameFr: "Norvège",
    nameAr: "النرويج",
    code: "NO",
    dialCode: "+47",
    },
    {
    flag: "🇴🇲",
    name: "Oman",
    nameFr: "Oman",
    nameAr: "عمان",
    code: "OM",
    dialCode: "+968",
    },
    {
    flag: "🇵🇰",
    name: "Pakistan",
    nameFr: "Pakistan",
    nameAr: "باكستان",
    code: "PK",
    dialCode: "+92",
    },
    {
    flag: "🇵🇼",
    name: "Palau",
    nameFr: "Palaos",
    nameAr: "بالاو",
    code: "PW",
    dialCode: "+680",
    },
    {
    flag: "🇵🇸",
    name: "Palestine",
    nameFr: "Palestine",
    nameAr: "فلسطين",
    code: "PS",
    dialCode: "+970",
    },
    {
    flag: "🇵🇦",
    name: "Panama",
    nameFr: "Panama",
    nameAr: "بنما",
    code: "PA",
    dialCode: "+507",
    },
    {
    flag: "🇵🇬",
    name: "Papua New Guinea",
    nameFr: "Papouasie-Nouvelle-Guinée",
    nameAr: "بابوا غينيا الجديدة",
    code: "PG",
    dialCode: "+675",
    },
    {
    flag: "🇵🇾",
    name: "Paraguay",
    nameFr: "Paraguay",
    nameAr: "باراغواي",
    code: "PY",
    dialCode: "+595",
    },
    {
    flag: "🇵🇪",
    name: "Peru",
    nameFr: "Pérou",
    nameAr: "بيرو",
    code: "PE",
    dialCode: "+51",
    },
    {
    flag: "🇵🇭",
    name: "Philippines",
    nameFr: "Philippines",
    nameAr: "الفيلبين",
    code: "PH",
    dialCode: "+63",
    },
    {
    flag: "🇵🇳",
    name: "Pitcairn",
    nameFr: "Pitcairn",
    nameAr: "بتكيرن",
    code: "PN",
    dialCode: "+64",
    },
    {
    flag: "🇵🇱",
    name: "Poland",
    nameFr: "Pologne",
    nameAr: "بولندا",
    code: "PL",
    dialCode: "+48",
    },
    {
    flag: "🇵🇹",
    name: "Portugal",
    nameFr: "Portugal",
    nameAr: "البرتغال",
    code: "PT",
    dialCode: "+351",
    },
    {
    flag: "🇵🇷",
    name: "Puerto Rico",
    nameFr: "Porto Rico",
    nameAr: "بورتوريكو",
    code: "PR",
    dialCode: "+1",
    },
    {
    flag: "🇶🇦",
    name: "Qatar",
    nameFr: "Qatar",
    nameAr: "قطر",
    code: "QA",
    dialCode: "+974",
    },
    {
    flag: "🇷🇪",
    name: "Réunion",
    nameFr: "Réunion",
    nameAr: "روينيون",
    code: "RE",
    dialCode: "+262",
    },
    {
    flag: "🇷🇴",
    name: "Romania",
    nameFr: "Roumanie",
    nameAr: "رومانيا",
    code: "RO",
    dialCode: "+40",
    },
    {
    flag: "🇷🇺",
    name: "Russia",
    nameFr: "Russie",
    nameAr: "روسيا",
    code: "RU",
    dialCode: "+7",
    },
    {
    flag: "🇷🇼",
    name: "Rwanda",
    nameFr: "Rwanda",
    nameAr: "رواندا",
    code: "RW",
    dialCode: "+250",
    },
    {
    flag: "🇧🇱",
    name: "Saint Barthélemy",
    nameFr: "Saint-Barthélemy",
    nameAr: "سان بارتيلمي",
    code: "BL",
    dialCode: "+590",
    },
    {
    flag: "🇸🇭",
    name: "Saint Helena",
    nameFr: "Sainte-Hélène",
    nameAr: "سانت هيلانة",
    code: "SH",
    dialCode: "+290",
    },
    {
    flag: "🇰🇳",
    name: "Saint Kitts and Nevis",
    nameFr: "Saint-Kitts-et-Nevis",
    nameAr: "سانت كيتس ونيفيس",
    code: "KN",
    dialCode: "+1869",
    },
    {
    flag: "🇱🇨",
    name: "Saint Lucia",
    nameFr: "Sainte-Lucie",
    nameAr: "سانت لوسيا",
    code: "LC",
    dialCode: "+1758",
    },
    {
    flag: "🇵🇲",
    name: "Saint Pierre and Miquelon",
    nameFr: "Saint-Pierre-et-Miquelon",
    nameAr: "سان بيير وميكلون",
    code: "PM",
    dialCode: "+508",
    },
    {
    flag: "🇻🇨",
    name: "Saint Vincent and the Grenadines",
    nameFr: "Saint-Vincent-et-les Grenadines",
    nameAr: "سانت فنسنت وجزر غرينادين",
    code: "VC",
    dialCode: "+1784",
    },
    {
    flag: "🇼🇸",
    name: "Samoa",
    nameFr: "Samoa",
    nameAr: "ساموا",
    code: "WS",
    dialCode: "+685",
    },
    {
    flag: "🇸🇲",
    name: "San Marino",
    nameFr: "Saint-Marin",
    nameAr: "سان مارينو",
    code: "SM",
    dialCode: "+378",
    },
    {
    flag: "🇸🇹",
    name: "São Tomé and Príncipe",
    nameFr: "Sao Tomé-et-Principe",
    nameAr: "ساو تومي وبرينسيبي",
    code: "ST",
    dialCode: "+239",
    },
    {
    flag: "🇸🇦",
    name: "Saudi Arabia",
    nameFr: "Arabie saoudite",
    nameAr: "المملكة العربية السعودية",
    code: "SA",
    dialCode: "+966",
    },
    {
    flag: "🇸🇳",
    name: "Senegal",
    nameFr: "Sénégal",
    nameAr: "السنغال",
    code: "SN",
    dialCode: "+221",
    },
    {
    flag: "🇷🇸",
    name: "Serbia",
    nameFr: "Serbie",
    nameAr: "صربيا",
    code: "RS",
    dialCode: "+381",
    },
    {
    flag: "🇸🇨",
    name: "Seychelles",
    nameFr: "Seychelles",
    nameAr: "سيشل",
    code: "SC",
    dialCode: "+248",
    },
    {
    flag: "🇸🇱",
    name: "Sierra Leone",
    nameFr: "Sierra Leone",
    nameAr: "سيراليون",
    code: "SL",
    dialCode: "+232",
    },
    {
    flag: "🇸🇬",
    name: "Singapore",
    nameFr: "Singapour",
    nameAr: "سنغافورة",
    code: "SG",
    dialCode: "+65",
    },
    {
    flag: "🇸🇽",
    name: "Sint Maarten",
    nameFr: "Saint-Martin",
    nameAr: "سانت مارتن",
    code: "SX",
    dialCode: "+1721",
    },
    {
    flag: "🇸🇰",
    name: "Slovakia",
    nameFr: "Slovaquie",
    nameAr: "سلوفاكيا",
    code: "SK",
    dialCode: "+421",
    },
    {
    flag: "🇸🇮",
    name: "Slovenia",
    nameFr: "Slovénie",
    nameAr: "سلوفينيا",
    code: "SI",
    dialCode: "+386",
    },
    {
    flag: "🇸🇧",
    name: "Solomon Islands",
    nameFr: "Îles Salomon",
    nameAr: "جزر سليمان",
    code: "SB",
    dialCode: "+677",
    },
    {
    flag: "🇸🇴",
    name: "Somalia",
    nameFr: "Somalie",
    nameAr: "الصومال",
    code: "SO",
    dialCode: "+252",
    },
    {
    flag: "🇿🇦",
    name: "South Africa",
    nameFr: "Afrique du Sud",
    nameAr: "جنوب أفريقيا",
    code: "ZA",
    dialCode: "+27",
    },
    {
    flag: "🇬🇸",
    name: "South Georgia and the South Sandwich Islands",
    nameFr: "Géorgie du Sud-et-les Îles Sandwich du Sud",
    nameAr: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    code: "GS",
    dialCode: "+500",
    },
    {
    flag: "🇰🇷",
    name: "South Korea",
    nameFr: "Corée du Sud",
    nameAr: "كوريا الجنوبية",
    code: "KR",
    dialCode: "+82",
    },
    {
    flag: "🇸🇸",
    name: "South Sudan",
    nameFr: "Soudan du Sud",
    nameAr: "جنوب السودان",
    code: "SS",
    dialCode: "+211",
    },
    {
    flag: "🇪🇸",
    name: "Spain",
    nameFr: "Espagne",
    nameAr: "إسبانيا",
    code: "ES",
    dialCode: "+34",
    },
    {
    flag: "🇱🇰",
    name: "Sri Lanka",
    nameFr: "Sri Lanka",
    nameAr: "سريلانكا",
    code: "LK",
    dialCode: "+94",
    },
    {
    flag: "🇸🇩",
    name: "Sudan",
    nameFr: "Soudan",
    nameAr: "السودان",
    code: "SD",
    dialCode: "+249",
    },
    {
    flag: "🇸🇷",
    name: "Suriname",
    nameFr: "Suriname",
    nameAr: "سورينام",
    code: "SR",
    dialCode: "+597",
    },
    {
    flag: "🇸🇿",
    name: "Swaziland",
    nameFr: "Swaziland",
    nameAr: "سوازيلاند",
    code: "SZ",
    dialCode: "+268",
    },
    {
    flag: "🇸🇪",
    name: "Sweden",
    nameFr: "Suède",
    nameAr: "السويد",
    code: "SE",
    dialCode: "+46",
    },
    {
    flag: "🇨🇭",
    name: "Switzerland",
    nameFr: "Suisse",
    nameAr: "سويسرا",
    code: "CH",
    dialCode: "+41",
    },
    {
    flag: "🇸🇾",
    name: "Syria",
    nameFr: "Syrie",
    nameAr: "سوريا",
    code: "SY",
    dialCode: "+963",
    },
    {
    flag: "🇹🇼",
    name: "Taiwan",
    nameFr: "Taïwan",
    nameAr: "تايوان",
    code: "TW",
    dialCode: "+886",
    },
    {
    flag: "🇹🇯",
    name: "Tajikistan",
    nameFr: "Tadjikistan",
    nameAr: "طاجيكستان",
    code: "TJ",
    dialCode: "+992",
    },
    {
    flag: "🇹🇿",
    name: "Tanzania",
    nameFr: "Tanzanie",
    nameAr: "تنزانيا",
    code: "TZ",
    dialCode: "+255",
    },
    {
    flag: "🇹🇭",
    name: "Thailand",
    nameFr: "Thaïlande",
    nameAr: "تايلاند",
    code: "TH",
    dialCode: "+66",
    },
    {
    flag: "🇹🇱",
    name: "Timor-Leste",
    nameFr: "Timor oriental",
    nameAr: "تيمور الشرقية",
    code: "TL",
    dialCode: "+670",
    },
    {
    flag: "🇹🇬",
    name: "Togo",
    nameFr: "Togo",
    nameAr: "توغو",
    code: "TG",
    dialCode: "+228",
    },
    {
    flag: "🇹🇰",
    name: "Tokelau",
    nameFr: "Tokelau",
    nameAr: "توكيلاو",
    code: "TK",
    dialCode: "+690",
    },
    {
    flag: "🇹🇴",
    name: "Tonga",
    nameFr: "Tonga",
    nameAr: "تونغا",
    code: "TO",
    dialCode: "+676",
    },
    {
    flag: "🇹🇹",
    name: "Trinidad and Tobago",
    nameFr: "Trinité-et-Tobago",
    nameAr: "ترينيداد وتوباغو",
    code: "TT",
    dialCode: "+1868",
    },
    {
    flag: "🇹🇳",
    name: "Tunisia",
    nameFr: "Tunisie",
    nameAr: "تونس",
    code: "TN",
    dialCode: "+216",
    },
    {
    flag: "🇹🇷",
    name: "Turkey",
    nameFr: "Turquie",
    nameAr: "تركيا",
    code: "TR",
    dialCode: "+90",
    },
    {
    flag: "🇹🇲",
    name: "Turkmenistan",
    nameFr: "Turkménistan",
    nameAr: "تركمانستان",
    code: "TM",
    dialCode: "+993",
    },
    {
    flag: "🇹🇨",
    name: "Turks and Caicos Islands",
    nameFr: "Îles Turques-et-Caïques",
    nameAr: "جزر توركس وكايكوس",
    code: "TC",
    dialCode: "+1649",
    },
    {
    flag: "🇹🇻",
    name: "Tuvalu",
    nameFr: "Tuvalu",
    nameAr: "توفالو",
    code: "TV",
    dialCode: "+688",
    },
    {
    flag: "🇺🇬",
    name: "Uganda",
    nameFr: "Ouganda",
    nameAr: "أوغندا",
    code: "UG",
    dialCode: "+256",
    },
    {
    flag: "🇺🇦",
    name: "Ukraine",
    nameFr: "Ukraine",
    nameAr: "أوكرانيا",
    code: "UA",
    dialCode: "+380",
    },
    {
    flag: "🇦🇪",
    name: "United Arab Emirates",
    nameFr: "Émirats arabes unis",
    nameAr: "الإمارات العربية المتحدة",
    code: "AE",
    dialCode: "+971",
    },
    {
    flag: "🇬🇧",
    name: "United Kingdom",
    nameFr: "Royaume-Uni",
    nameAr: "المملكة المتحدة",
    code: "GB",
    dialCode: "+44",
    },
    {
    flag: "🇺🇸",
    name: "United States of America",
    nameFr: "États-Unis",
    nameAr: "الولايات المتحدة",
    code: "US",
    dialCode: "+1",
    },
    {
    flag: "🇺🇾",
    name: "Uruguay",
    nameFr: "Uruguay",
    nameAr: "أوروغواي",
    code: "UY",
    dialCode: "+598",
    },
    {
    flag: "🇺🇿",
    name: "Uzbekistan",
    nameFr: "Ouzbékistan",
    nameAr: "أوزبكستان",
    code: "UZ",
    dialCode: "+998",
    },
    {
    flag: "🇻🇺",
    name: "Vanuatu",
    nameFr: "Vanuatu",
    nameAr: "فانواتو",
    code: "VU",
    dialCode: "+678",
    },
    {
    flag: "🇻🇦",
    name: "Vatican City",
    nameFr: "Cité du Vatican",
    nameAr: "مدينة الفاتيكان",
    code: "VA",
    dialCode: "+379",
    },
    {
    flag: "🇻🇪",
    name: "Venezuela",
    nameFr: "Venezuela",
    nameAr: "فنزويلا",
    code: "VE",
    dialCode: "+58",
    },
    {
    flag: "🇻🇳",
    name: "Vietnam",
    nameFr: "Vietnam",
    nameAr: "فيتنام",
    code: "VN",
    dialCode: "+84",
    },
    {
    flag: "🇼🇫",
    name: "Wallis and Futuna",
    nameFr: "Wallis-et-Futuna",
    nameAr: "واليس وفوتونا",
    code: "WF",
    dialCode: "+681",
    },
    {
    flag: "🇪🇭",
    name: "Western Sahara",
    nameFr: "Sahara occidental",
    nameAr: "الصحراء الغربية",
    code: "EH",
    dialCode: "+212",
    },
    {
    flag: "🇾🇪",
    name: "Yemen",
    nameFr: "Yémen",
    nameAr: "اليمن",
    code: "YE",
    dialCode: "+967",
    },
    {
    flag: "🇿🇲",
    name: "Zambia",
    nameFr: "Zambie",
    nameAr: "زامبيا",
    code: "ZM",
    dialCode: "+260",
    },
    {
    flag: "🇿🇼",
    name: "Zimbabwe",
    nameFr: "Zimbabwe",
    nameAr: "زيمبابوي",
    code: "ZW",
    dialCode: "+263",
    },
    ];
   };